version: '3.4'

services:
  alpine-siab-hobo:
    image: REGISTRY_BASE_URL/alpine-siab:latest
    hostname: 'hobo'
    environment:
      - "domainname=idocker.REALM_DOMAIN_SUFFIX"
      - "HL_USER_USERNAME=hacker"
      - "HL_USER_PASSWORD=compass"
      - "HL_ROOT_PASSWORD=dQ0edEdD6dWZMJj"
